imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    filters:
        less:
            node:       /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to:   "\.less$"
        sass:
            ruby:       "/usr/local/Cellar/ruby/1.9.3-p362/bin"
            bin:        "/usr/local/Cellar/ruby/1.9.3-p362/bin/sass"
            apply_to:   "\.(scss)$"
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            datetime: Bc\Bundle\DoctrineBundle\DBAL\Type\UTCDateTimeType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

bc_user:
    db_driver:     orm  # Sets fos_user.db_driver
    firewall_name: main # Sets fos_user.firewall_name
    registration:
        enabled:         true # If FALSE registration is not possible
        invite_required: true # If TRUE invite is required for registration
    request_invite:
        form:
            type:    bc_user_request_invite
            handler: bc_user.request_invite.form.handler.default
            name:    bc_user_request_invite_form
            validation_groups:
                - RequestInvite

